embree: Autospec creation for update from version 3.12.0 to version 3.13.4
Brecht Van Lommel (4):
      Arm: add sse2neon library
      Arm: add __64BIT__ define to identify 64 bit processors of any vendor
      Arm: add __X86_ASM__ define to identify processors that support X86 asm
      Arm: support Arm CPUs by emulating SSE2 instructions with Neon

CI-env-update (1):
      Introduce TutorialData to grid geometry tutorial.

Carsten Benthin (14):
      making subgrid moeller and pluecker intersector more similar and simpler
      making pluecker intersector interface more like moellertrumbore, e.g. calling epilog now outside the real intersect fct
      fixing sse2 path
      modified pluecker tri intersector to be used for subgrid intersector
      single ray subgrid pluecker intersector now relies only on tri intersector
      removing explicit intersect1 from subgrid packet intersector
      packet based sub grid intersector based purely on tri intersector, also added occludedK for subgrids
      cleanups
      consistency again between single and packet normals
      more fixes
      subgrid moeller trumberbore intersector only uses tri intersectors similar to pluecker
      added lossy grids paper to doc
      updated doc
      removed alpha.0 from version note in cmake

Developer-Ecosystem-Engineering (5):
      Restore AVX2 via 2xNEON support for Apple silicon
      Use SIMD256 on CPU::ARM
      Revert "Use SIMD256 on CPU::ARM"
      Revert "Restore AVX2 via 2xNEON support for Apple silicon"
      Restore AVX2 via 2x NEON support for Apple silicon

Donna Nemshick (1):
      Update spec.md

Eric Stollnitz (3):
      Fixed #359: Support compiling to WebAssembly using Emscripten
      Allow choice of EMBREE_TASKING_SYSTEM in emscripten.
      Fix parallel_partition test on WASM.

Florian Reibold (69):
      silently ignore if setaffinity fails.
      fix PATH for oneTBB 2021.1-beta08 on windows.
      add oneTBB 2021.1-beta08 and ispc 14.1 tests.
      install all files matching libtbb.*
      fix findTBB for oneTBB and search for tbb12.dll on windows
      upgrade oneTBB-2021.1-beta to oneTBB-2021.1.1
      updates for OSPRay integration test
      refactor benchmarking system
      fix model dir copy for add_subdirectory build
      add uninstall target only if not already defined
      convert algorithms from object to static lib
      use provided TBBConfig.cmake for onetbb
      port all algorithm tests to Catch
      update changelog
      disable all but benchmark in CI
      test benchmark repetitions
      less benchmarks (faster testing)
      numactl fix
      dummy change
      test new benchmark setup
      dummy change
      only run barbarian_msmblur_instancing
      reduce test intensity to 0
      benchmark other scenes again
      increase benchmark repetitions
      run all the benchmarks
      dummy change
      dummy change 2
      Update .gitlab-ci.yml
      Update .gitlab-ci.yml
      Update .gitlab-ci.yml
      Update .gitlab-ci.yml
      Update .gitlab-ci.yml
      reduce benchmark load
      dummy change
      test tbb 2020.3
      back to oneTBB 2021.1
      test running benchmarks automatically when scheduled but otherwise manually
      take Embree regression benchmarks online
      don't find system wide tbb install when EMBREE_TBB_ROOT is set
      insert suites and subsuites
      fix typo in doc
      update dependency versions
      copy tbb dlls into executable folder.
      also update ospray in release test
      try to copy TBB dll only if it exists
      update ispc 1.13 to 1.15 and TBB 2021.1.1 to 2021.2.0 in release tests
      update Embree version and changelog.md
      fix command line ordering issue for benchmark
      fix bug with empty child at beginning of child list
      reenable ray stats (e.g. MRays/s) for legacy benchmark mode
      split configure, test, and build stage in CI
      bugfix in emulated ray packet intersection when EMBREE_RAY_PACKETS is
      bugfix for linear quaternion interpolation fallback.
      changelog
      Fix occlusion query bug in subgrid intersector for ray packets
      changelog
      don't alias -i and -c command line options for benchmarking
      add support for icx (oneapi intel dpcpp compiler) on linux
      change dpcpp fp-mode to precise (same as clang's default)
      add ICX test on windows
      fix MY_PROJECT_BINARY_DIR in case of icx compiler
      use specific ICX version under Windows
      add threads:N argument to test.py configure stage
      improve handling of ICX/DPCPP on linux
      TBB 2021.5.0 might cause nondeterministic segfaults in CI test.
      run windows ICX job with less threads to pervent out of memory error
      disable ICX on windows and replace TBB 2021.5.0 with 2021.2.0
      don't define dll_export/dll_import when building Embree as a static

Johannes Günther (2):
      Updates to readme.pdf (Intel style)
      Relax disclaimers

Johannes Meng (1):
      unique_ptr constructor is explicit.

Krzysztof Raszkowski (6):
      ci: increase severity in klocwork check script
      ci: change protex script to use env
      ci: align kw check to requirements & add kw issues report
      ci: add binary scans for release jobs
      ci: change interpretation of bdba verdict N/A as accepted
      Add SECURITY.md file

Lyuma (1):
      Fix typos in #if and nonstandard implicit cast.

Robert Cohn (2):
      conversion to sphinx/rst for inclusion in oneapi-spec
      fix some restructuredText issues

Rémi Verschelde (4):
      Fix undefined reference to `GridMesh` with `EMBREE_GEOMETRY_GRID` off
      thread: Add initial support for Android
      sys: Fixes for MinGW support
      Don't override `NOMINMAX` and `likely` if already defined

Sean C McDuffee (3):
      update changelog for
      update to latest icc and tbb
      remove old nightlies

Sean McDuffee (2):
      check for non-manifoldness when checking border
      Resolve "get ICC on new mac-mini's working"

Sebastian Herholz (1):
      adding support for user defined TBB library names

Solomon Boulos (1):
      Fix Newton-Raphson iteration for rcp() w/ AVX2.

Stefan Werner (1):
      Fixed operator precedence in sin() and cos()

Sven Woop (222):
      setting version to v3.12.1-alpha.0
      fixing error message for static build of multi-ISA Embree under MacOSX to Clang >= 9.0.0
      fixing path to NAS on macOS
      introducing TutorialData object for instancing_geometry tutorial
      introducing TutorialData for user geometry tutorial.
      setting version to v3.12.1
      setting default frequency level for skylake server CPUs to simd128
      updated documentation
      renamed RTC_NAMESPACE_OPEN -> RTC_NAMESPACE_USE
      removed export maps, these are no longer required
      Revert "removed export maps, these are no longer required"
      better matching of user defined namespace in map file
      docu mentions all ISPC versions we test
      updates to map files
      added support to detect Tiger Lake CPUs
      changed default frequency level for Skylake, Kaby Lake, Comet Lake, and Tiger Lake to SIMD128 for higher clock frequencies
      using enum classes for CPU model
      updated docu of frequency_level
      doing some CI testing with enforced frequency level simd128 and simd256
      fixed typo in test.py script
      fixed typo of RTC_DEVICE_PROPERTY_JOIN_COMMIT_SUPPORTED in docu
      removed some dependencies from python scripts
      workaround to respect alignment of tbb:task_group
      regenerated documentation
      running klockwork scan also in nightly testing
      running CI only on embree runners
      supporting vfloat<1> -> float instantiation etc.
      compile fixes for multi instancing
      cleanups to instance_stack.h
      introducing UVMapper to moeller trumbore intersector
      fixed compile warning
      fixed wrong instance_id_stack::copy usage
      fixed ICC compile issue
      fixed further ICC compile issue
      moving rtcInterpolate implementation into headers
      workaround for gcc compile issue
      introduced TutorialData struct in interpolation tutorial
      fix in filename.h
      using primRefGen for Grids
      updates to triangle intersectors, more general mapUV
      fixed oneTBB 2021 version detection bug
      avoiding to use _mm_extract_ps intrinsic to extract float, as that intrinsic returns an integer
      consistently drawing with same camera in view and write to disk mode, y=0 is on top of image always
      disabled klockwork scan temporarily
      removed KNL optimizations
      removed AVX512KNL
      removed KNL optimization to calculate SIMD4/8 also with SIMD16
      Renamed AVX512SKX to official name AVX512. Old CMake setting AVX512SKX works still for compatibility.
      enabled klocwork test again, but allowing failure
      disabled continuous-macosx-x64-Debug-ICC2020.1-ISPC1.14.1-SSE2-TBB2021.1-beta08 test, it runs very slow
      splitted curve_intersector_virtual.cpp file to improve compile times
      fixed some missed renames of avx512skx to avx512
      error checking in condition implementation
      fixed some potential division by zero issues
      fixed for klockwork update
      fixed potential division by zero issues
      enabling klockwork test again
      using notarization login from gitlab environment variables
      Added grid intersector changes to changelog.
      updated copyright headers to 2021
      changed further copyright year
      renamed verify to embree_verify
      added Bella Renderer to projects.md file
      simplifications to test.py script
      removed benchmark.py script
      installing cmake files to cmake/embree-version folder also in ZIP mode
      fix for Windows
      fixed broken include in docu
      using TBB2021.1.1 for release build
      setting version to v3.12.2
      updated documentation
      setting version to v3.12.3-alpha.0
      signing only on some macs
      increasing clamscan limits to properly scan macOS packages
      Revert "disable all but benchmark in CI"
      removed support for .embree3 config files
      added SSE2NEON to third-party-programs.txt
      updated python to python3 in scripts
      switched more portableg /usr/bin/env python3 in python scripts
      started SIMD wrapper cleanups, cleaning up unused functions in vfloat16_avx512.h
      removed unused broadcast4f/8f functions
      removed unused code from vfloat16_avx512.h
      removed some unused compact/assign/broadcast2
      removed some broadcast, store_uchar, notand
      removed compact64bit which should not be inside vint vector class
      removed broadcast64bit function which should not be inside vint vector class
      removed extract64bit function which should not be inside vint vector class
      removed KNL specific code
      removed xchg function from SIMD wrappers
      removed unused test function from SIMD wrappers
      removed glfw3.h include from voronoi tutorial
      testing ARM code in CI
      disabling setAffinity on macOS with M1, seems not supported
      supporting EMBREE_MAX_ISA=DEFAULT/NONE in ARM mode
      Arm -> ARM
      CI bugfix for ARM
      added cornell_box_instanced model
      using fast min/max for NEON
      using NEON fmadd
      using fast NEON math when __aarch64__ is defined
      added ARM to changelog
      cleanups to ARM support in main CMakeLists.txt
      more ARM related updates to docu
      using proper floor/ceil/trunc implementation for ARM
      performance optimization for ARM traversal
      added support for multi_level instancing mode to scene conversion and viewer
      cleanups to scene_device.cpp
      Cleaned up instance handling. ISPCScene matches structure of canonical scenegraph now.
      checking if scene instancing depth is smaller than configured maximal instancing depth
      removed scene member of ISPCGeometry structure
      geometries that are referenced multiple times by scene graph are just created once
      added multi level instancing support to pathtracer
      executing all command line scene graph operations after device construction
      fixed wrong usage of ray.instID instead of dg.instID in pathtracer
      regenerated tutorials
      setting policy CMP0072 to NEW
      fixed memory leak, scene graph is now destroying referenced ISPC objects
      fix for Win32 compilation
      extended XML writer to support text format
      added first version of camera animation
      introduced SceneGraph::PerspectiveCameraData struct
      linear blending between camera animation time stamps
      added time_range to camera animation
      making base scene graph light structs non-virtual, and putting all virtual functions to SceneGraph::LightNode
      added animated light support to scene graph
      added animation support to viewer
      added support for light animation
      linear interpolation for instance and light animation
      supporting camera motion when using non-animated camera from XML file
      fixed Win32 struct alignment issue
      assignShadersFunc should get executed after rtcCommitGeometry
      using visited flag during ISPCScene conversion
      constructing Embree object inside ISPC struct constructor
      introducing commit function for each ISPC object
      fixed memory leak in hair_geometry tutorial
      moving transform animation code to scene graph
      keeping current transform up to data during animation
      simplified instance animation code
      Avoiding spatial split positions that are out of geometry bounds.
      removed old spatial binning code
      fixed potential corner case in spatial split position fix
      fixed some issues reported by memory checker
      properly handling number of allowed splits during binning
      introduced rtcGetGeometryThreadSafe function
      Fixed more places where less accurate Newton raphson iteration for rcp was used
      bugfix to darray_t implementation
      bugfix to pre-splitter
      updates to changelog
      setting version to v3.13.2
      regenerated documentation
      more testing with ISPC 1.16.1
      fixed compile warning
      fixed ISPC compile warnings
      fixed bugs with btc/bts/btr instrinsic implementation on ARM platform
      using default CMAKE_INSTALL_NAME_DIR
      allowing manual release builds
      fixed typo in documentation
      Invalid multi segment motion blurred normal oriented curves are properly excluded from BVH build.
      setting version to v3.13.3-alpha.0
      fixed wrong assertion in presplitter
      using proper Intel® ISPC naming in documentation
      using proper download path for TBB
      find_package no longer requires Embree version
      Fixed crash caused by disabling a geometry and then detaching it from the scene.
      disabling valgrind CI test as it runs too slow, clang address sanitizer testing should be sufficient
      fixing embree-config.cmake for static compilation when multi-ISA enabled
      removing scripts/release scripts, these are not used
      no longer building MSI and PKG installers for release
      fixing more places where spaces in filenames made potential issues
      added WebAssembly CI test
      removed some space in path fixes that cause issues
      This commit fixes an issue with normal oriented curve construction, caused by large
      fixed issues with increased compare-threshold for sponza model
      using ISPC 1.17.0
      Upgrading to oneTBB 2021.5.0 for release build.
      fixed typo in TBB version 2021.5.0 under Windows
      disabling sponza CI testing
      updates to changelog
      setting version to v3.13.3
      regenerated documenation
      adding support for comments in CI models file
      running nightly CI also for web pipeline triggers
      added Intel® oneAPI DPC++/C++ Compiler 2022.0.0 as supported compiler
      disabled ICX Windows CI for now
      invoking reportIntersection1/reportOcclusion1 via direct call in rtcore.cpp
      no longer passing InternalContext to user geometry callbacks
      bugfix to compile with recent GCC
      added more generic interface to parallel_for and parallel_for_for_prefix_sum
      using constexpr for constant definitions
      fixed DPCPP detection by executable name matching
      Fixed binning related crash in SAH BVH builder.
      added CI testing for NEON AVX2 mode
      removed -fms-extensions as this causes issues with WebAssembly build
      using neon-i32x8 target for ISPC when EMBREE_NEON_AVX2_EMULATION is enabled
      enabling ISPC on Apple NEON again
      using 8-wide BVH when EMBREE_NEON_AVX2_EMULATION is enabled
      making EMBREE_NEON_AVX2_EMULATION configurable
      compile fix for EMBREE_NEON_AVX2_EMULATION disabled
      replacing prod_diff by msub again
      removed special store/storeu aarch64 case
      removed special insert/extract functions for aarch, there are already functions that perform the same operation
      cleanups to vboolf8_avx and verify.cpp
      restored original common/sys/vector.h
      rtcore.cpp no longer using std::mutex just for Apple, we will switch to std::mutex at some later point
      no longer using c++17 under macOS
      removed some constants that were already present in mm_lookupmask_ps
      removed more less important constants
      removed more less important constants
      replaced _mm_movemask_popcnt_ps by faster version
      consistently using fmadd/fmsub on NEON, this improves performance further
      restoring scene.cpp
      minor cleanups
      restoring macosx-version-min to 10.7
      restoring kernels/common/default.h
      adding NEON2X cmake ISA config for ARM
      only enabling AVX2 when using AVX2NEON on MacOS
      added Apple M1 performance optimization to changelog
      updates to changelog
      setting version to v3.13.4
      updated documentation
      compile fixes for Windows
      fixed potential issues with ARM compilation under Linux

Trevor Thomson (4):
      Set CMake Project version to 3.13.1
      Upgrade to tbb 2021.3.0 and ispc 1.16.1 for releases (and latest dependency versions for ospray test)
      Rebuilt documentation
      Roll back dependency version upgrades in ospray test

Will Usher (3):
      ISPC+ARM support
      ISPC+ARM support
      Add handling for Intel oneAPI DPCPP compiler, do not treat as clang

Yixing Lao (1):
      Fix compiler check for oneAPI C++ compiler

ashpil (1):
      fix build error if built in directory with spaces

cbenthin (5):
      branch for fixing grid normal orientation error reported by framestore
      more fixes in subgrid_pluecker intersector
      quick test for windows
      test workaround for poential compiler bug
      correct bug fix in sse mode

luz paz (1):
      Fix various typos

visuser (1):
      fixed accuracy of rsqrt when using NEON